### ISSUE TITLE
QUESTION: json.schemas -> fileMatch

### ISSUE THREAD

**Issue by tomitrescak** [skolmer/vscode-i18n-tag-schema#3]
Hi, while I managed to understand most of the functionality and I really admire your work, I do not understand what does json.schemas -> fileMatch do. I know it needs to point to json files with my translations, but what do I need it for? Thanks!

**Comment by skolmer** [comment]
Let me try to give you a bit of an explanation what the goal of this tool and i18n-tag-schema in general is. The idea behind this extensions and the underlying node based command line tool (https://github.com/skolmer/i18n-tag-schema) is to give you the opportunity to translate your applications after you finished your development process without any extra effort in keeping track of all your translatable content. I believe that everyone knows how painful it can be to translate a JavaScript application afterwards and if you try to do so how easy it is to miss some of the content you want to translate. Even if you put translation keys into your code while you are developing you can easily mess up the translations with a simple typo or a missing key. It is also really hard to keep track of your translation progress and quality. This tool tries to solve these common problems.
The basic idea is that whenever you write a string in JavaScript that might potentially need translation afterwards you just decorate your string with a tag. Instead of writing `"hello"` you just write `i18n`hello`` and that's it. No extra effort to keep track of this string or any translation keys that you might miss in the translation process. 
While the tag allows me to automatically collect all translatable content from the source code the generated schema allows me to check if a translation is valid or if there are still parts in the application that need to be translated. So the basic idea is to build a schema that checks which strings in your application exist, which are translated and for strings that include template expression like `hello ${name}` you can even check if your translation contains all the required parameters.
This is the basic concept of i18n tags and the JSON schema.
To answer your question, vscode provides JSON schema based features like JSON validation and autocompletion out of the box. The only thing you have to do is to tell vscode which schema you want to use and where your JSON files are located that you want vscode to check. 
Lets take the basic example from the README:

```
    "json.schemas": [
        {
            "fileMatch": [
                "/src/i18n/*.json"
            ],
            "url": "./translation.schema.json"
        }
    ]
```

`fileMatch` tells vscode where your JSON files are located and the `url` points to the schema that vscode should use to check validity of the JSON files that match the `fileMatch` pattern. 
You should note that there is an alternative to this kind of configuration. You can instead tell vscode which schema to use if you add a `$schema` key directly into your JSON file like this:

```
{
    "$schema": "./translation.schema.json"
}
```

I hope this helps to understand the whole scope of this project and the underlying configuration. 
If you have any more questions feel free to ask.

**Comment by tomitrescak** [comment]
@skolmer thanks for the explanation. I am alraeady actively using this and works really nicely. It works with no issues with Typescript as well. The only thing that does not work is showing the current translations in the active file, as it is currently limited to JS files.  Good job!

**Comment by skolmer** [comment]
@tomitrescak thank you for your kind feedback, really appreciate it!
I hope to get rid of some limitations in the current i18n-tag-schema version while improving test coverage. I will post further updates on the following issue: https://github.com/skolmer/i18n-tag-schema/issues/9
